#!/usr/bin/env sh

SEMVER=`buildtools/versionize`
VERSIONTYPE=`buildtools/versionize --type`

echo "Build version $SEMVER ($VERSIONTYPE)"

mkdir ./artifacts

cd ./vscode-extension
pnpm version $SEMVER --no-git-tag-version --allow-same-version --no-git-checks
if [ "$VERSIONTYPE" = "preview" ]; then
   npm pkg set preview='true'
fi
pnpm ci
pnpm build:vsix -o ../artifacts/ilspy-vscode-$SEMVER.vsix

echo "// ILSpy VSCode Extension, v$SEMVER" > ../artifacts/extension-types.ts
cat src/extension-types.ts >> ../artifacts/extension-types.ts

echo "// ILSpy VSCode Extension, v$SEMVER" > ../artifacts/extension-api.ts
cat src/extension-api.ts >> ../artifacts/extension-api.ts
