#!/usr/bin/env sh

SEMVER=`dotnet dotnet-gitversion -showvariable SemVer`
PRERELEASETAG=`dotnet dotnet-gitversion -showvariable PreReleaseTag`

mkdir ./artifacts

cd ./vscode-extension
npm version --git-tag-version false --allow-same-version true -- $SEMVER
if [[ -n "$PRERELEASETAG" ]]; then
   npm pkg set preview='true'
fi
pnpm install
pnpm build:vsix -- -o $VSIX_FILENAME
