#!/usr/bin/env sh

SEMVER=`dotnet dotnet-gitversion -showvariable SemVer`

mkdir ./artifacts

cd ./vscode-extension
npm version --git-tag-version false --allow-same-version true -- $SEMVER
npm install
npm run package
npm install @vscode/vsce -g
vsce package -o ../artifacts/ilspy-vscode-$SEMVER.vsix
