#!/usr/bin/env sh

dotnet publish ./backend/ILSpyX.Backend.LSP/ILSpyX.Backend.LSP.csproj --configuration Release --self-contained false -p:UseAppHost=false -p:CIBuild=true --output ./vscode-extension/bin/ilspy-backend
