#!/usr/bin/env sh

buildtools/versionize

dotnet publish ./backend/src/ILSpy.Backend/ILSpy.Backend.csproj --configuration Release --self-contained false -p:UseAppHost=false --output ./vscode-extension/bin/ilspy-backend
