#!/usr/bin/env sh

dotnet tool restore

SEMVER=`dotnet dotnet-gitversion -showvariable SemVer`
ASSEMBLY_VERSION=`dotnet dotnet-gitversion -showvariable NuGetVersionV2`
ASSEMBLY_FILEVERSION=`dotnet dotnet-gitversion -showvariable AssemblySemFileVer`

update_csproj() {
    echo "<Project>" > ./backend/Directory.Build.props
    echo "    <PropertyGroup>" >> ./backend/Directory.Build.props
    echo "        <Version>$ASSEMBLY_VERSION</Version>" >> ./backend/Directory.Build.props
    echo "        <FileVersion>$ASSEMBLY_FILEVERSION</FileVersion>" >> ./backend/Directory.Build.props
    echo "    </PropertyGroup>" >> ./backend/Directory.Build.props
    echo "</Project>" >> ./backend/Directory.Build.props
}

update_package_json() {
    pushd vscode-extension
    npm version --git-tag-version false --allow-same-version true -- $SEMVER
    popd
}

update_package_json
update_csproj