name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Full Unicode check
        if: github.ref == 'refs/heads/master'
        run: buildtools/unicode-check --all

      - name: PR-based Unicode check
        if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/pull/')
        run: buildtools/unicode-check

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2.0
        with:
          dotnet-version: 10.0.x

      - name: Check .NET Core version
        run: dotnet --version

      - name: Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb #v6.0.0
        with:
          run_install: false
          package_json_file: vscode-extension/package.json

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: "22"
          cache: 'pnpm'
          cache-dependency-path: vscode-extension/pnpm-lock.yaml

      - name: Bootstrap Build Tools
        run: buildtools/bootstrap

      - name: Publish Backend
        run: buildtools/publish-backend

      - name: Test Backend
        run: buildtools/test-backend

      - name: Test Extension
        run: buildtools/test-extension

      - name: Build Extension
        run: buildtools/build-vsix

      - name: Archive artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #7.0.0
        with:
          name: Artifacts
          path: artifacts/*

      - name: Create draft release
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" --draft --title "${GITHUB_REF#refs/tags/v}" artifacts/*.vsix
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
